name: Run SQL on Fabric (DEV)

on:
  workflow_dispatch:

jobs:
  run-sql-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run SQL on Fabric (DEV)
        run: |
          docker run --rm mcr.microsoft.com/mssql-tools \
            /opt/mssql-tools/bin/sqlcmd \
            -S ${{ secrets.SQL_SERVER }} \
            -d ${{ secrets.SQL_DATABASE }} \
            -G \
            -Q "SELECT GETDATE();"

      - name: Run DEV SQL
        run: |
          sqlcmd -S ${{ secrets.SQL_SERVER }} \
                 -d ${{ secrets.SQL_DATABASE }} \
                 -G \
                 -U ${{ secrets.CLIENT_ID }} \
                 -P ${{ secrets.CLIENT_SECRET }} \
                 -i sql/dev.sql
