name: Run SQL on Fabric (DEV)

on:
  workflow_dispatch:

jobs:
  run-sql:
    runs-on: ubuntu-latest

    env:
      SQL_SERVER: ${{ secrets.SQL_SERVER }}
      SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull sqlcmd image
        run: docker pull mcr.microsoft.com/mssql-tools

      - name: Run CREATE TABLE script
        run: |
          docker run --rm \
            mcr.microsoft.com/mssql-tools:latest \
            /opt/mssql-tools/bin/sqlcmd \
            -S $SQL_SERVER \
            -d $SQL_DATABASE \
            -G \
            -U $CLIENT_ID \
            -i sql/create_table.sql

      - name: Run INSERT metadata script
        run: |
          docker run --rm \
            mcr.microsoft.com/mssql-tools:latest \
            /opt/mssql-tools/bin/sqlcmd \
            -S $SQL_SERVER \
            -d $SQL_DATABASE \
            -G \
            -U $CLIENT_ID \
            -i sql/insert_metadata.sql
