name: Run SQL on Fabric

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        type: choice
        options:
          - DEV
          - TEST
          - PROD

jobs:
  run-sql:
    runs-on: ubuntu-latest

    env:
      SQL_SERVER: ${{ secrets[format('SQL_SERVER_{0}', inputs.environment)] }}
      SQL_DATABASE: ${{ secrets[format('SQL_DATABASE_{0}', inputs.environment)] }}
      CLIENT_ID: ${{ secrets[format('CLIENT_ID_{0}', inputs.environment)] }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull sqlcmd image
        run: |
          docker pull mcr.microsoft.com/mssql-tools

      - name: Run CREATE TABLE script
        run: |
          docker run --rm \
            mcr.microsoft.com/mssql-tools:latest \
            /opt/mssql-tools/bin/sqlcmd \
            -S $SQL_SERVER \
            -d $SQL_DATABASE \
            -G \
            -U $CLIENT_ID \
            -i sql/create_table.sql

      - name: Run INSERT metadata script
        run: |
          docker run --rm \
            mcr.microsoft.com/mssql-tools:latest \
            /opt/mssql-tools/bin/sqlcmd \
            -S $SQL_SERVER \
            -d $SQL_DATABASE \
            -G \
            -U $CLIENT_ID \
            -i sql/insert_metadata.sql
