name: Run SQL on Fabric (DEV)

on:
  workflow_dispatch:

jobs:
  run-sql-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install sqlcmd
        run: |
          docker pull mcr.microsoft.com/mssql-tools

      - name: Run CREATE TABLE script
        run: |
          docker run --rm \
            -e SQLCMDPASSWORD="${{ secrets.CLIENT_SECRET }}" \
            mcr.microsoft.com/mssql-tools \
            /opt/mssql-tools/bin/sqlcmd \
            -S ${{ secrets.SQL_SERVER }} \
            -d ${{ secrets.SQL_DATABASE }} \
            -U ${{ secrets.CLIENT_ID }} \
            -G \
            -i sql/create_table.sql


      - name: Run INSERT metadata script
        run: |
          docker run --rm \
            -e SQLCMDPASSWORD="${{ secrets.CLIENT_SECRET }}" \
            mcr.microsoft.com/mssql-tools \
            /opt/mssql-tools/bin/sqlcmd \
            -S ${{ secrets.SQL_SERVER }} \
            -d ${{ secrets.SQL_DATABASE }} \
            -U ${{ secrets.CLIENT_ID }} \
            -G \
            -i sql/insert_metadata.sql
